name: Coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm run lint:fix
      - run: npm test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3